### ISSUE TITLE
Work as a team

### ISSUE THREAD

**Issue by 3mp3yjms** [celenny/celenny#1]
@celenny want to work as a team

**Comment by celenny** [comment]
Hello @ 3mp3yjms! If I can contribute, yes I’m always open to learning more and thanks for the invitation

**Comment by 3mp3yjms** [comment]
The project is about finding a unique input

**Comment by celenny** [comment]
> @celenny quer trabalhar em equipe
Hello @ 3mp3yjms! could you tell me about the project and thanks for the invitation.

**Comment by celenny** [comment]
@3mp3yjms  Wow ! this looks interesting how could I help you ?

**Comment by 3mp3yjms** [comment]
Think of creating a input battle between code inputs that if they keep mixing up like colors that a extraordinary display will emerge
@celenny

**Comment by 3mp3yjms** [comment]
Where are you from

**Comment by celenny** [comment]
> Think of creating a input battle between code inputs that if they keep mixing up like colors that a extraordinary display will emerge
> @celenny

Hi @3mp3yjms , I’d love to contribute to your project, but I still feel like a beginner. I hope it continues and maybe in the future you’ll show me the results and I can help. Thank you so much 👽🖖🏾
